config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show]

  resources :travels

  put '/travels/:id/publish' => 'travels#publish', as: :publish
  put '/travels/:id/hide' => 'travels#hide', as: :hide

  get 'search/:keywords' => 'travels#index', as: :search
  get 'tags/:tag' => 'travels#index', as: :tag

  get '/home' => 'pages#home', as: '/'
  get '/about' => 'pages#about', as: 'about'

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/travel.rb
class Travel < ApplicationRecord
  acts_as_taggable
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  mount_uploader :facade, FacadeUploader
    validates :title, length: {in: 4..40}, uniqueness: {case_sensitive: false}
    validates :content, length: {in: 150..7000}
    validates :facade, file_size: { less_than: 5.megabytes }
    validates :tag_list, length: {minimum: 1, message: 'Debe haber al menos una etiqueta'}

    belongs_to :user

    scope :most_recent, -> { order(published_at: :desc) }
    scope :published, -> { where(published: true) }
    scope :with_title, ->(title) {
      where("travels.title LIKE ?","%#{title}")
    }
    scope :by_year_and_month, ->(year, month) {
      date = Date.new(year,month)
      where(published_at: date..date.next_month)
    }
    scope :by_months_ago, ->(months) {
      where(published_at: months.month.ago.beginning_of_month..months.month.ago.end_of_month)
    }

    default_scope { where(published: true) and order(published_at: :desc) }

    def publish
      update(published: true, published_at: Time.now)
    end

    def hide
      update(published: false, published_at: nil)
    end
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged,:finders]
  #attr_accessor :slug

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, uniqueness: {case_sensitive: false}
  validates :slug, uniqueness: true
  #validates_date :dob, :before => lambda { 18.years.ago  },
      #:before_message => "must be at least 18 years old"

  has_many :travels

  def should_generate_new_friendly_id?
    new_record? || slug.nil? || slug.blank? # you can add more condition here
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :get_last_travels

  before_action :sanitize_devise_params, if: :devise_controller?

  def sanitize_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private
    def get_last_travels
      today = Date.today
      current_month = today.month
      @travels_per_month = 0.upto(5).map { |n|
        Travel.by_months_ago(n)
      }
      @displayed_months = 6.downto(1).map { |n|
        DateTime::MONTHNAMES.drop(1)[(current_month - n)] % 12
      }
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @last_travel = Travel.first
    @slides_providers = Travel.published.most_recent.first(4)
  end

  def about
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :set_travel, only: [:show, :destroy, :publish, :hide]
  before_action :authenticate_user!, except: [:show, :index] # with devise method

  # GET /travels
  # GET /travels.json
  def index
    if params[:tag]
      @travels = Travel.published.tagged_with(params[:tag])
      flash[:notice] = "No hay viajes con esta etiqueta." unless @travels
    elsif params[:keywords]
      @travels = Travel.with_title(params[:keywords])
      flash[:notice] = "No hay viajes que coincidan con esta búsquea." unless @travels
    else
      @travels = Travel.most_recent.published
    end
  end

  def search
  end

  # GET /travels/1
  # GET /travels/1.json
  def show
  end

  # GET /travels/new
  def new
    @travel = Travel.new
  end

  # GET /travels/1/edit
  def edit
    @travel = current_user.travels.friendly.find(params[:id])
    redirect_to root_path, alert: 'El artículo referenciado no puede editarse.' unless @travel
  end

  def publish
    @travel.publish
    render :edit
  end

  def hide
    @travel.hide
    render :edit
  end

  # POST /travels
  # POST /travels.json
  def create
    @travel = current_user.travels.new(travel_params)

    respond_to do |format|
      if @travel.save
        format.html { redirect_to @travel, notice: 'Travel was successfully created.' }
        format.json { render :show, status: :created, location: @travel }
      else
        format.html { render :new }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /travels/1
  # PATCH/PUT /travels/1.json
  def update
    @travel = current_user.travels.find_by_id(params[:id])
    respond_to do |format|
      if @travel.update(travel_params)
        format.html { redirect_to @travel, notice: 'Travel was successfully updated.' }
        format.json { render :show, status: :ok, location: @travel }
      else
        format.html { render :edit }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travels/1
  # DELETE /travels/1.json
  def destroy
    @travel.destroy
    respond_to do |format|
      format.html { redirect_to travels_url, notice: 'Travel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_travel
      @travel = Travel.friendly.find(params[:id])
    end

    def set_travel_publish
      @travel = Travel.find_by_id(params[:travel_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def travel_params
      params.require(:travel).permit(:title, :content, :facade, :tag_list)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
		options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer,extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_archive.html.erb
<div class="archive <%= archive_position %>">

  <% @travels_per_month.each_with_index do |travels, n| %>
    <div class="archive-entry">
      <span class="glyphicon glyphicon-play toggle-display" aria-hidden="true"></span>
      <%= link_to @displayed_months.reverse[n], travels_path %>
      <ul class="archive-hide">
        <% if !travels.empty? %>
          <% travels.each do |travel| %>
            <li><%= link_to travel.title.truncate(30), travel %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>

</div>

app/views/layouts/_header.html.erb
<!-- page header -->
<div id="header">
  <a href="/home" class="page-brand"><img src="/assets/logo.png" alt="" id="logo"></a>
  <% if user_signed_in? %>
    <span class="login">Signed in as <%= link_to current_user.name, current_user %></span>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete, :class => 'btn btn-default login' %>
  <% else %>
    <%= link_to 'Sign up!', new_user_registration_path, :class => 'btn btn-default login' %>
    <%= link_to 'Log in', new_user_session_path, :class => 'btn btn-default login' %>
  <% end %>
  <ul class="social-links">
    <li><a href="https://www.facebook.com/"><img src="/assets/logo-facebook.png"></a></li>
    <li><a href="https://www.twitter.com/"><img src="/assets/logo-twitter.png"></a></li>
    <li><a href="https://www.plus.google.com/"><img src="/assets/logo-googleplus.png"></a></li>
  </ul>
  <h1>Low Travel</h1>
</div>
<!-- /page header -->

app/views/layouts/_navbar.html.erb
<nav id="navigate" class="navbar" data-spy="affix" data-offset-top="<%= navbar_offset %>">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'LowTravel', root_path, class: 'main-link collapsed navbar-toggle' %>
    </div>

    <div class="collapse navbar-collapse" id="collapse">
      <ul class="nav navbar-nav nav-justified">
        <li class="active"><%= link_to 'Inicio', root_path %></li>
        <li><%= link_to 'Viajes', travels_path %></li>
        <li><%= link_to 'LowCost', travels_path(tag: 'lowcost') %></li>
        <li><%= link_to 'Internacional', travels_path(tag: 'internacional') %></li>
        <li>
          <%= form_tag travels_path, class: 'navbar-form', method: :get do %>
              <%= search_field_tag :keywords, params[:keywords], class: 'form-control', placeholder: 'Buscar...' %>
            <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_slider.html.erb
<div id="slider" class="carousel slide" data-ride="carousel" data-interval="4300">
  <% if @slides_providers.count > 0 %>
    <ol class="carousel-indicators">
      <% @slides_providers.each_with_index do |travel,i| %>
        <li data-target="#slider" data-slide-to="<%= i %>" class="<%= i == 0 ? 'active' : '' %>"></li>
      <% end %>
    </ol>

    <div class="carousel-inner">
      <% @slides_providers.each_with_index do |travel,i| %>
        <div class="item <%= i == 0 ? 'active' : '' %>">
          <% if travel.facade.present? %>
            <%= image_tag(travel.facade) %>
          <% else %>
            <img src="http://placehold.it/1200x315" alt="...">
          <% end %>
          <div class="carousel-caption">
            <h3><%= link_to travel.title, travel %></h3>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_tags.html.erb
<%# renders a p with the content of the tags %>
<% if travel.tag_list.count == 0 %>
  <p class="empty-tags">Este viaje no tiene etiquetas.</p>
<% else %>
  <p class="tags">Etiquetas: <%= raw travel.tag_list.map{ |t| link_to t, tag_path(t) }.join(', ') %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LowTravel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div id="content-container" class="container-fluid">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "flash #{key} message" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<%= render partial: 'layouts/slider' %>
<% if @slides_providers.count > 0 %>
  <%= render partial: 'layouts/navbar', locals: {navbar_offset: 370} %>
<% else %>
  <%= render partial: 'layouts/navbar', locals: {navbar_offset: 70} %>
<% end %>

<div class="row single-column-row">
  <div class="col-md-3">
    <%= render partial: 'layouts/archive', locals: {archive_position: "left"} %>
  </div>
  <div class="col-md-6 travel text-center">
    <% if !@last_travel.nil? %>
      <%= render @last_travel %> 
    <% else %>
      <h2>There are no posts yet <span class="glyphicon glyphicon-plane"></span></h2>
      <%= link_to 'Why not share your own?', new_travel_path %>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/travels/_form.html.erb
<%= render partial: 'layouts/navbar', locals: {navbar_offset: 70} %>
<%= form_for(travel) do |f| %>
  <% if travel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(travel.errors.count, "error") %> prohibited this travel from being saved:</h2>

      <ul>
        <% travel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# ----------------------------------- %>

  <div class="row single-column-row travel-form">
    <div class="col-md-4 travel-fields">
      <% if travel.new_record? %>
        <h2>New Travel</h2>
      <% else %>
        <h2>Editing: "<%= link_to travel.title, travel %>"</h2>
      <% end %>
      <br>
      
      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :tag_list, "Etiquetas (separadas por comas)" %><br>
        <%= f.text_field :tag_list, value: travel.tag_list.to_s %>
      </div>
      <div class="field">
        <%= f.label :facade %><br>
        <%= f.file_field :facade %>
      </div>
      <div class="actions">
        <%= f.submit %>
        <% if !travel.new_record? %>
          <% if !travel.published and !travel.new_record? %>
            <%= link_to 'Publish', publish_path(travel), method: :put, class: 'public' %>
          <% else %>
            <%= link_to 'Hide', hide_path(travel), method: :put, class: 'public' %>
            <%= link_to 'Delete travel', travel, method: :delete, data: { confirm: "This action cannot be undone. Do you want to continue?" }, class: 'public' %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-8">
      <div>
        <%= f.text_area :content %>
      </div>
      <p class="message">This content is actually be written in <a href="https://daringfireball.net/projects/markdown/">Markdown</a>. If you want to make it prettier, here is a useful <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">guide</a>.</p>
    </div>
  </div>

<% end %>

app/views/travels/_indexed.html.erb
<% if travels.empty? %>
  <h2>There are no posts yet <span class="glyphicon glyphicon-plane"></span></h2>
  <%= link_to 'Why not share your own?', new_travel_path %>
<% end %>
<% travels.each do |travel| %>
  <div class="row single-column-row travel-index">
    <div class="col-sm-4 travel-info">
      <% if travel.facade.present? %>
        <%= link_to image_tag(travel.facade) if travel.facade.present? %>
      <% else %>
        <img src="/assets/thumbnail-placeholder-300x300" alt="">
      <% end %>
      <h3><%= link_to travel.title, travel %> 
    </h3>
    <% if current_user == travel.user %>
      <p><%= link_to 'Edit', edit_travel_path(travel)%></p>
    <% end %>
    <p>by <%= User.find_by_id(travel.user_id).name %></p>
    <%= render partial: 'layouts/tags', locals: {travel: travel} %>
    </div>
    <div class="col-sm-8 travel-content text-justify">
      <p><%= markdown(truncate(travel.content, length: 600, separator: ' ', omission: '... ') {"[sigue leyendo](#{travel_path(travel)})"}) %></p>
    </div>
  </div>
<% end %>

app/views/travels/_travel.html.erb
<div class="travel well">

  <%# ---- This was a piece of work. Showing some respect ---- %>

  <div class="facade-container" data-toggle="modal" data-target="#gallery">
    <div class="facade-image">
      <%= image_tag(travel.facade) if travel.facade.present? %>
    </div>
    <h2 class="facade-link">
      <%= link_to travel.title, travel_path(travel) %>
      <small>by <%= link_to travel.user.name, travel.user %></small>
    </h2>
  </div>

  <%# -------- %>

  <hr>
  <div class="text-justify">
    <p>Publicado el <%= travel.published_at.to_date if travel.published? %></p>
    <p><%= markdown(travel.content) %></p>

    <hr>
    <%= render partial: 'layouts/tags', locals: {travel: travel} %>
    <% if travel.user == current_user %>
      <%= link_to 'Edit', edit_travel_path(travel), class: 'edit-travel' %>
    <% end %>

    <div id="gallery" class="modal fade" tabindex="-1" aria-labelledby="imageGallery">
      <div class="row single-column-row above-modal">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <%= image_tag(travel.facade) if travel.facade.present? %>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/travels/edit.html.erb
<%= render 'form', travel: @travel %>

app/views/travels/index.html.erb
<%= render partial: 'layouts/navbar', locals: {navbar_offset: 70} %>
<div class="row single-column-row">
  <%= link_to 'New Travel', new_travel_path, class: 'link-new' %>
  <div class="col-md-8 col-md-offset-1">
    <%= render 'indexed', travels: @travels %>
  </div>
  <div class="col-md-3">
    <%= render partial: 'layouts/archive', locals: {archive_position: "right"} %>
  </div>
</div>

<br>

app/views/travels/new.html.erb
<%= render 'form', travel: @travel %>

<%= link_to 'Back', travels_path %>

app/views/travels/show.html.erb
<%= render partial: 'layouts/navbar', locals: {navbar_offset: 70} %>
<div class="row single-column-row">
  <div class="col-md-2">
    <%= render partial: 'layouts/archive', locals: {archive_position: "left"} %>
  </div>
  <div class="col-md-8">
    <%= render @travel %>
  </div>
  <div class="col-md-2">
  </div>
</div>

<%= link_to 'All travels', travels_path %>

app/views/users/show.html.erb
<%= render partial: 'layouts/navbar', locals: {navbar_offset: 70} %>
<div class="row single-column-row profile">
  <div class="col-md-2">
    <div class="facade-container">
      <div class="facade-image avatar">
        <%= link_to image_tag("/assets/traveller-placeholder-300x300"), notice: 'This functionality is not yet implemented' %>
      </div>
      <h2 class="facade-link">
        <%= link_to @user.name ,edit_user_registration_path(@user) %>
        <span class="glyphicon glyphicon-pencil" style="font-size:60%;"></span>
      </h2>
    </div>

  </div>
  <div class="col-md-8 col-md-offset-2">
    <%= render 'travels/indexed', travels: @user.travels %>
  </div>
  </div>
</div>